name: CMCS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Keep this job as is
    ...

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: cmcs-image:latest
        outputs: type=docker,dest=/tmp/cmcs-image.tar

    - name: Load Docker image
      run: |
        docker load --input /tmp/cmcs-image.tar
        docker image ls -a

    - name: Run Docker container
      run: |
        docker run -d -p 32768:8080 -p 32769:8081 --name prog6212_cmcs_st10082 cmcs-image:latest
        docker ps
